### PR TITLE
Implement Track Events

### LINKED ISSUE #232: Implement new tracking events
There is a list of WooCommerce Tracking events we would like to trigger in the plugin, to be able to analyze how the plugin is being used.
A comprehensive list of all events is available at https://docs.google.com/spreadsheets/d/1u25mOcsODgcdPMy_rIagUAWHCfzsvJI1e8UPrJvYtVE/edit#gid=903716843

### Describe the solution you'd like 

- [x] Ensure all the dependencies and libraries needed are in place and in up-to-date versions.
- [ ] Implement individual events (each should be prefixed with `wcadmin_pfw_`): 
   - [x] `page_view`	n/a		When viewing wc react powered page. Default wc-admin event.
   - [x] ~`disconnected_account_link_click`~ `account_disconnect_button_click { context: 'settings' }` (see [below](https://github.com/woocommerce/pinterest-for-woocommerce/issues/232#issuecomment-1002184777))			When acocunt is disconnected rom the setting page https://d.pr/i/s7Oh7T  https://github.com/woocommerce/pinterest-for-woocommerce/pull/313
   - [x] `documentation_link_click`			When clicking documentation link e.g. https://d.pr/i/nSI71V, https://d.pr/i/COCw3G  and https://d.pr/i/plH2LQ 	https://github.com/woocommerce/pinterest-for-woocommerce/pull/261		
   - [x] `get_started_faq`			Clicking on getting started page faq item to collapse or expand it https://d.pr/i/CP6WPF - https://github.com/woocommerce/pinterest-for-woocommerce/pull/237
   - [x] `get_started_notice_link_click`			Clicking on a text link within the notice on the Get Started page https://d.pr/i/NWRC2W  https://github.com/woocommerce/pinterest-for-woocommerce/pull/299
   - [ ] `help_click`		**Not needed yet**	Triggered when the "Help" button is clicked.
   - [x] `account_connect_button_click`			https://d.pr/i/E3rtBZ - https://github.com/woocommerce/pinterest-for-woocommerce/pull/239
   - [x] `account_create_button_click`			https://d.pr/i/E3rtBZ  - https://github.com/woocommerce/pinterest-for-woocommerce/pull/239
   - [x] `modal_closed`			Triggered when a modal is closed https://github.com/woocommerce/pinterest-for-woocommerce/pull/290
   - ~[ ] `modal_content_link_click`			Triggered when clicking on a text link within the modal content~ currently there is no link in the modal.
   - [x] `modal_open`			Triggered when a modal is opened/displayed https://d.pr/i/AUJddy https://github.com/woocommerce/pinterest-for-woocommerce/pull/290
   - [x] `save_changes_button_click`			Triggered when save changes button is clicked https://d.pr/i/4CiZgY https://github.com/woocommerce/pinterest-for-woocommerce/pull/295
   - [x] `setup`			Triggered on events during setup e.g. get start button click https://d.pr/i/HGg9Mj  or header buttons clicked https://d.pr/i/7BlNRu or continue button e.g. https://d.pr/i/wADg9P https://d.pr/i/YoyLP2  https://github.com/woocommerce/pinterest-for-woocommerce/pull/308
   - [x] `domain_verify_failure`			When a site verification fails https://github.com/woocommerce/pinterest-for-woocommerce/pull/300
   - [x] `domain_verify_success`			When a site is successfully verified https://d.pr/i/4NLnzy  https://github.com/woocommerce/pinterest-for-woocommerce/pull/314
   - [ ] `able_header_toggle`		**not needed yet**	When table columns/headers are toggle by a user e.g. Product Feed table
   - [ ] `table_sort`		**not needed yet**	When table column is sorted by a user
   - [ ] `table_go_to_page`		**not needed yet**	When table pagination is changed by "Go to page" input
   - [ ] `table_page_click`		**not needed yet**	When table pagination is clicked
   - [ ] `tooltip_viewed`		**not needed yet**	When a tooltip (helptip) is viewed/clicked
- [x] (Nice to have) Implement some automation for translating code docs for events to aggregated docs. https://github.com/woocommerce/google-listings-and-ads/issues/117 - https://github.com/woocommerce/pinterest-for-woocommerce/pull/238

Additional ones, implemented by the way:
- Account related https://github.com/woocommerce/pinterest-for-woocommerce/pull/239
	 - `account_convert_button_click`
	 - `account_disconnect_button_click`
	 - `account_create_button_click`
	 - `business_account_connect_button_click`
- [x] `wcadmin_pfw_ads_manager_link_click` When _"Pinterest ads manager"_ link is clicked [more...](https://github.com/woocommerce/pinterest-for-woocommerce/pull/296#pullrequestreview-842872047) https://github.com/woocommerce/pinterest-for-woocommerce/pull/316

### Feature branch

The feature will be tracked at https://github.com/woocommerce/pinterest-for-woocommerce/tree/feature/232-tracking

### Additional context 

- Existing issue related to Pinterest JS tracking https://github.com/woocommerce/pinterest-for-woocommerce/issues/28

//cc @jconroy

### PR DESCRIPTION
**Pull request by tomalec**
### Changes proposed in this Pull Request:

This PR implements Track Events, and doc generation tool.

The work was already reviewed in respective PRs

Closes https://github.com/woocommerce/pinterest-for-woocommerce/issues/232

### Screenshots:
image

### Detailed test instructions:

Individual changes were tested in their PRs, so we mainly need to.
1. Smoke test the plugin.

### Changelog entry

> Add Tracking Events.
> Add JSDoc plugin to generate Tracking Events documentation.

### CODE REVIEW

**Review by puntope — COMMENTED** [review]
👀  Please check warnings and questions before merging. 

- I was able to activate/deactivate the plugin ✅ 
- I was able to disconnect my account✅ 
- I was able to connect my account✅ 
- I was able to create a new account✅ 
- My site was claimed automatically for an existing domain✅ 
- I was able to access and click on documentation links ✅ 
- I was able to update my settings✅ 
- I was able to navigate between tabs after onboarding✅ 
- It shows Account disapproved, I did an appeal and it shows a waning notice "Please hold on tight as there is an Appeal pending for your Pinterest account." ✅ 
- I can disconnect my account from settings✅ 
- I can open and close faq items✅ 
- I can access and click on Terms of service✅ 
- I cannot claim the URL if it was claimed by other user ❓ 
- Entering a new Domain URL maintained my connection and allowed me to verify my domain✅   
- After finishing, it shows "Please hold on tight as your account is pending approval from Pinterest. This may take up to 5 business days"✅ 

Tested again this tracks:
- wcadmin_pfw_account_disconnect_button_click ✅ 
- wcadmin_pfw_modal_open ✅ 
- wcadmin_pfw_modal_closed ✅  
- wcadmin_pfw_setup ✅ 
- wcadmin_pfw_documentation_link_click ⚠️ Se comments after....
- wcadmin_pfw_save_changes_button_click ✅ 
- wcadmin_page_view ✅ 
- wcadmin_pfw_get_started_faq ✅ 
- wcadmin_pfw_domain_verify_success ✅ 
- wcadmin_pfw_domain_verify_failure ✅ 


⚠️ Not sure if this should be done, but when I clicked on Catalog -> Pinterest ads manager(opens in a new tab). It didn't trigger `wcadmin_pfw_documentation_link_click`. Same with the "feed" link. 

Screenshot 2022-01-03 at 17 11 58

**Comment by tomalec** [comment]
> :warning: Not sure if this should be done, but when I clicked on Catalog -> Pinterest ads manager(opens in a new tab). It didn't trigger `wcadmin_pfw_documentation_link_click`. Same with the "feed" link.

This is not a documentation page, so I'd rather add a new, separate event `wcadmin_pfw_ads_manager_link_click`.

**Comment by tomalec** [comment]
> I cannot claim the URL if it was claimed by other user :question:

Could you provide more details? I suspect this might be a separate issue not related to events, and not broken here.

**Comment by puntope** [comment]
> > I cannot claim the URL if it was claimed by other user ❓
> 
> Could you provide more details? I suspect this might be a separate issue not related to events, and not broken here.

Steps:

1. Create an account with a valid and claimed domain
2. Disconnect that account
3. Create a new Pinterest account
4. On website claim it returns an error regarding "This URL is already claimed" which for example in GLA allows us to re-claim it for the new setup.

Not sure if it's actually expected or its an issue. If it's not related. I would go ahead and create a separated issue if needed.

**Review by puntope — APPROVED** [review]

**Comment by puntope** [comment]
✅  Besides my 2 comments that after asking, they are probably out scope this looks ready fro me.

**Comment by findingsimple** [comment]
> This is not a documentation page, so I'd rather add a new, separate event wcadmin_pfw_ads_manager_link_click.

Lets do that 👍

**Comment by findingsimple** [comment]
> On website claim it returns an error regarding "This URL is already claimed" which for example in GLA allows us to re-claim it for the new setup.

> Not sure if it's actually expected or its an issue. If it's not related. I would go ahead and create a separated issue if needed.

I don't think reclaiming is part of the functionality provided by Pinterest but I could be wrong. Can you create a new issue for investigation - we'll need to confirm - but I don't think it should block here unless it is being effected by the events triggering.

**Pull request merged**
