### PR TITLE
Update promo code

### LINKED ISSUE #864: Switch over coupon code for 2024
For ads credit claiming feature switch over to new coupon code for 2024

Use old code in 2023. and Switch over to new code in 2024 in production

### PR DESCRIPTION
**Pull request by budzanowski**
### Changes proposed in this Pull Request:

Updarte promo code for 2024

Closes #864 

### Additional details:

Not active yet.

### Changelog entry

> Update - promo code for 2024

### CODE REVIEW

**Comment by message-dimke** [comment]
Hey, @budzanowski !

Do we care about timezones?

**Comment by budzanowski** [comment]
@message-dimke we do. I am waiting for answer from Pinterest.

**Comment by budzanowski** [comment]
@message-dimke this is now timezone correct and precise to a second.
I have clarified that the zone is GMT and the exact moment of switch is GMT Dec 31, 2023  23:59:59

**Review by message-dimke — APPROVED** [review]
LGTM! Thank you, @budzanowski

**Pull request merged**
