### PR TITLE
Take taxes into account in tracking events

### LINKED ISSUE #402: product price mismatch for some websites
### Steps to reproduce:

1. Visit https://dagelijksebroodkruimels.nl/webshop/christelijke-boeken/bijbelse-dagboeken/dagboek-dagelijksebroodkruimels/
2. Add to cart
3. look at add to cart events

### Expected behavior:
The price should be same as shown in website

### Actual behavior:
The price is different in the event sent

### Additional details:
Screen Shot 2022-03-18 at 3 41 12 PM

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #402.

Fix the product's price mismatch if the prices are shown including taxes or not.
- Fix the price mismatch on shop and product pages, also on cart and checkout.
- Fix the price mismatch on feed file (the price on feed will be the same than shop and product pages).

### Detailed test instructions:
1. Install the plugin and do the onboarding.
2. Set the options 'Display prices in the shop' and 'Display prices during cart and checkout' to 'Including tax' located on WooCommerce Settings -> Tax -> Tax Options.
3. Visit a product page and add to cart a product.
4. The price shown in the tracking events should be the same than product page and cart.
5. Verify that the price is also correct on the feed file.

### Additional details:

> Fix - Price mismatch when price includes taxes.

### CODE REVIEW

**Comment by alexiglesias31** [comment]
@jconroy, the PR is ready for review.

**Review by mikkamp — APPROVED** [review]
Thanks for these changes, the code looks good.

I have a test product which costs 10 EUR with a tax of 10% so I'm expecting to see it displayed as 11 when it shows inclusive of taxes.

For the events that matches:
```
event: pagevisit
ed: {"product_id":72,"product_name":"Test Product","product_price":11}

event: AddToCart
ed: {"product_id":72,"product_name":"Test Product","value":11,"order_quantity":1,"currency":"EUR"}

event: checkout
ed: {"order_id":75,"value":33,"order_quantity":2,"currency":"EUR","line_items":[{"product_id":1,"product_name":"Test Product","product_price":11,"product_quantity":2,"product_category":["Test Category"]}]}
```

Although I noticed that the checkout event is setting `product_id` to the order item ID, that should be getting it from the product instead (seeing a 1 where I expect a 72).

The prices also match in the feed:
```xml
<item>
	<g:id>72</g:id>
	<title>
		<![CDATA[ Test Product ]]>
	</title>	
	<g:product_type>Test Category</g:product_type>
	<g:price>11.00EUR</g:price>
```

When I switch back to displaying without taxes they all show up with a value of 10 instead. But I noticed that the rich pins always show the product as 10 regardless of whether it should be including taxes:
```html
<meta property="og:title" content="Test Product" />
<meta property="product:price:currency" content="EUR" />
<meta property="product:price:amount" content="10" />
```
Should that be updated as well?

**Comment by alexiglesias31** [comment]
Thank you @mikkamp. Good catches.
Just updated according to your comments:

> Although I noticed that the checkout event is setting `product_id` to the order item ID, that should be getting it from the product instead (seeing a 1 where I expect a 72).

Update to read the `product_id`.

> When I switch back to displaying without taxes they all show up with a value of 10 instead. But I noticed that the rich pins always show the product as 10 regardless of whether it should be including taxes:

Update the price on the rich pins to take into account the included taxes.

**Review by mikkamp — APPROVED** [review]
Thanks for the additional changes, those are working, I get the price correctly in the rich pins now.

```xml
<meta property="og:title" content="Test Product" />
<meta property="product:price:currency" content="EUR" />
<meta property="product:price:amount" content="11" />
```

This looks good to merge after the conflict is resolved.

**Pull request merged**
