### PR TITLE
Add onboarding eligibility notice 

### LINKED ISSUE #515: Ads Credit Flow: Onboarding Eligibility Notice
_Work In Progress Issue_

## User story

As a product manager
I want to incentivize Merchants to continue setting up Pinterest for WooCommerce
So that they have the motivation to finish onboarding

As a merchant
I want to be incentivized to complete set up of Pinterest for WooCommerce
So that I am willing to continue to spend my valuable time/money finishing onboarding

### Description

We would like to display a clear notice during the onboarding flow notifying merchants of their eligibility for Ads Credit e.g. "Get $100 Credit...."

Screen Shot 2022-08-23 at 8 45 36 pm

## Technical

* Use tracks event functionality already within the extension
* Where possible utilize existing WordPress/WooCommerce components (icons etc.)

Please use the [feature/ads-credit-flow](https://github.com/woocommerce/pinterest-for-woocommerce/tree/feature/ads-credit-flow) branch for targeting prs against.

## Figma link

[https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3417%3A56425](https://www.figma.com/file/ojzkxOhHQnIZx4QjsFH5Zy/Native-Pinterest-Integration?node-id=3417%3A56425)

## Acceptance criteria

* [ ] Component visually matches design
* [ ] Component scales responsively in an appropriate manner (@shivanarrthine to confirm)
* [ ] Tracks event fired when clicking "View terms" link

## Unknowns

* Terms and conditions link to provided - can use placeholder link to get development started
* Copy to be confirmed

## Out of bounds/rabbit holes

* Ideally we can pull Campaign values e.g. $100 programmatically from API - for version 1 of this feature we'll just hard code to meet deadlines.

## Dependency

* TBC

## Event tracking

* `event_name` - Clicking view terms link should trigger tracks event

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #515.

Implement eligibility notice on connect account step as described in the issue description. As described in the issue, the link is a placeholder for now.

### Screenshots:

image

### Detailed test instructions:
1. Install the plugin.
2. Go to the first step of the onboarding.
3. The eligibility notice should be displayed.
4. The event should be tracked when the link is clicked.

### Changelog entry

> Add - Onboarding eligibility notice for ad credits

### CODE REVIEW

**Review by sc-ecolasurdo — APPROVED** [review]

**Comment by findingsimple** [comment]
Thank you!

**Comment by budzanowski** [comment]
We are putting this on hold for now. I need to confirm how this fits into the newest design?

**Comment by alexiglesias31** [comment]
Turn it in a Draft PR

**Comment by findingsimple** [comment]
> I need to confirm how this fits into the newest design?

Still part of the design. The copy just needs to be updated

**Comment by budzanowski** [comment]
@alexiglesias31 I will update the copy.

**Comment by budzanowski** [comment]
Note: rebased with `feature/ads-credit-flow`

**Review by budzanowski — APPROVED** [review]

**Pull request merged**
