### PR TITLE
Track redeem credits event

### LINKED ISSUE #578: Ads Credit, track coupon redeem flow.
Coupon redeem operation should be tracked. 

Investigate the best place for coupon redeem action tracking and the format of tracking.
We want minimal info, we just want to check if the users are actually getting value from this flow.

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #578.

Track redeem credits event.

### Detailed test instructions:
1. Install a build of this PR.
2. Do the onboarding and redeem the credits.
3. The redeem credits event should be tracked.

### CODE REVIEW

**Comment by budzanowski** [comment]
We want to track bot success and failure scenario.
I think that we could move the tracking from the `redeem_credits` to the `add_redeem_credits_info_to_account_data` method. This way we will be able to also track status and the error parameters.

**Review by budzanowski — CHANGES_REQUESTED** [review]
Please add tracking to all of the results.

**Comment by alexiglesias31** [comment]
In that case, we can track all the `$redeem_information`, or do you think we should unset advertiser_id, username and id?

**Comment by budzanowski** [comment]
@alexiglesias31 that is a good call! We should not track anything that allows us to identify the user. We want to be GDPR safe. Coupon id, redeem status ( success, failure ), error code. We can also drop error message because it is equivalent to the error code.

**Comment by alexiglesias31** [comment]
@budzanowski done

**Review by budzanowski — APPROVED** [review]

**Pull request merged**
