### PR TITLE
Add update procedure

### LINKED ISSUE #584: Ads credit, plugin update behaviour.
Investigate and implement how the code should behave when this is deployed on merchant site as a plugin update and not fresh setup. Things to consider:

- modals display behaviour
- redemption behaviour ( will cyclic check be OK or we should maybe try to do the setup during update procedure )
- everything else that comes to mind.

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #584.

Integrate the ad credits flow to users that already has the plugin installed.

### Detailed test instructions:
1. Install the live version of the plugin and do the onboarding.
2. Update to a build version of this PR.
3. The modals should be displayed.

### CODE REVIEW

**Comment by alexiglesias31** [comment]
@budzanowski
This is a first approach for the plugin update.
As far as I understand, after the plugin update the modals will be displayed, since the `ads_modal_dismissed` parameter will not be set.
I'd bet for redeem the credits during the update procedure, but please let me know your thoughts.

**Comment by budzanowski** [comment]
@alexiglesias31 I wonder if we should not hide the modal on update and rely only on banners. 
I will ask the designer.

**Comment by budzanowski** [comment]
I have confirmed that the modals should not be shown for users that are updating the plugin. Only the post-onboarding messages on the Catalog page should be used. This means that we probably can just create dismiss options during the update procedure.

**Comment by alexiglesias31** [comment]
Thanks for the clarification @budzanowski 
Should we keep the credits redeem during the update procedure too? Or just the dismiss options and the redeem can be scheduled normally with the daily heartbeat?

**Comment by budzanowski** [comment]
I think that daily heartbeat is a good idea.

**Review by budzanowski — APPROVED** [review]

**Pull request merged**
