### PR TITLE
Fix/fatal error rest cart

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Fix fatal error for rest calls: https://wordpress.org/support/topic/fatal-error-4386/

### Changelog entry

> Fix - Fatal error if cart is not set.

### CODE REVIEW

**Review by message-dimke — APPROVED** [review]
Looks good! Thanks, @alexiglesias31 !

**Comment by message-dimke** [comment]
Hey, @alexiglesias31 ! 
When `isset` successfully tests against `null` I am curious if it is a better idea to test `WC()->cart` to be a `WC_Cart` instance since there is a call to its method immediately after the condition is successful. `Null` is maybe better that instance of a class, since it will throw a Fatal when calling a method which does not exist rather than introducing an unexpected behaviour which could be harder to track down. In case of checking agains the instance of a `WC_Cart` class we must also log the mismatch not to crash user's website. What do you think?

Other than that looks good and I approved it already.

**Comment by alexiglesias31** [comment]
Hey @message-dimke, as an extra layer of stability yes, I think we could use `method_exists` instead, that way we ensure there won't be any mismatch and if for some reason, the cart is not null but the method doesn't exist, then the value will be read from the WC settings.
Wdyt?

**Review by message-dimke — APPROVED** [review]
LGTM!

**Pull request merged**
