### PR TITLE
Add automerge-released-trunk workflow

### PR DESCRIPTION
**Pull request by tomalec**
_This PR is a copy of https://github.com/woocommerce/automatewoo/pull/1509_

### Changes proposed in this Pull Request:

Add automerge-released-trunk workflow to automate merging trunk to develop after a release.

This is to remove the need for manual work like this one https://github.com/woocommerce/automatewoo/pull/1506

### Screenshots:

image

### Detailed test instructions:

1. Merge this PR :see_no_evil: or fork repo with this branch merged
2. Create a release PR with `woocommerce/grow/prepare-extension-release` action
3. Merge the release PR
4. Check that release was merged from trunk to develop

### Changelog entry

> Dev - automate merging trunk to develop after a release.

### CODE REVIEW

**Comment by tomalec** [comment]
Unfortunately, if you have branch protection set up action bot would not be able to do the push.

**Review by layoutd — APPROVED** [review]
⭐  Very nice! Worked well in my forked repo (after some finagling with the prepare release workflow).
image

I wonder if having this action means this line 
```
1. [ ] Merge \`trunk\` to \`develop\` (PR), if applicable for this repo.
```
should move from [woo-extension-create-pr-for-release.mjs](https://github.com/woocommerce/grow/blob/cc99f597771d139ab2c5650e0d867bf27ad49dbc/packages/github-actions/actions/prepare-extension-release/src/woo-extension-create-pr-for-release.mjs#L60) to the `post-steps` in [the example yml](https://github.com/woocommerce/grow/blob/cc99f597771d139ab2c5650e0d867bf27ad49dbc/packages/github-actions/actions/prepare-extension-release/README.md?plain=1#L49)

**Comment by tomalec** [comment]
> I wonder if having this action means this line […]

In most (if not all) Automata repos, we have branch protection rules that prevent auto-merge workflow from running. Therefore, we need a manual step to merge to `trunk`. 
It could be guided with automatically created PR by https://github.com/woocommerce/grow/tree/cc99f597771d139ab2c5650e0d867bf27ad49dbc/packages/github-actions/actions/merge-trunk-develop-pr, but that's still a step to take.

I hope _"if applicable for this repo"_ covers the case of the auto-merged repos as (not applicable) ;)

**Comment by tomalec** [comment]
Before merging, could you check the branch protection rules for this repo? I don't have access there.
https://github.com/woocommerce/automatewoo/settings/branches

Something like this will most likely prevent this workflow from running
image

**Comment by layoutd** [comment]
@tomalec Looks like it should be OK for now:

`trunk`:
image
`develop`:
image

**Pull request merged**
