### PR TITLE
Retry mechanism for feed generation

### LINKED ISSUE #563: When merchant's feed take more than 24hs to generate, the feed is never updated or created.
### Describe the bug:
This happens when merchants have more than 800k products and variants. After 24h the previous execution didn't finish and start the new one, so this creates an endless loop.

### Steps to reproduce:
1. Site with 800k products
2. install and do the onboarding with the Pinterest plugin

### Expected behavior:
New execution of feed generation should not be executed until the last one was finished.

### Actual behavior:
the feed never is updated or created.

### Additional details:
SauCal ticket: https://saucal.zendesk.com/agent/tickets/10637
WooCommerce ticket: #5206946

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #563.

An error during the feed generation breaks the generation process. This PR adds a retry mechanism to avoid that the generation process breaks.

### Screenshots
image

### Detailed test instructions:
1. Install a build version of this PR.
2. Add the following snippet to the site (the snippet will break the feed generation in the first batch):
```
add_filter( 'pinterest_for_woocommerce_excluded_product_types', function() {
	throw new Exception( 'This is a test Exception' );
} );
```
3. The feed generation should apply the retry mechanism on the first batch after the failure.
4. The retry details should be available in the logs (`pinterest-for-woocommerce-sync`).

### Changelog entry

> Fix - Add retry mechanism for the feed generation.

### CODE REVIEW

**Review by sc-ecolasurdo — APPROVED** [review]

**Comment by alexiglesias31** [comment]
Hey @budzanowski @message-dimke, this PR is ready for review.

**Comment by alexiglesias31** [comment]
@message-dimke I added the timeout handler. The timeout was not blocking the generation before the feed, but no info was provided to the user. The new update calls to `handle_error` after a timeout.

**Comment by alexiglesias31** [comment]
Hey @message-dimke I added a small refactor on the retry mechanism + timeout test.

**Review by message-dimke — APPROVED** [review]
Hey, @alexiglesias31 ! Looks good, thank you!

**Comment by message-dimke** [comment]
Hey, @alexiglesias31 ! Is this one ready to be merged or are we waiting for something?

**Comment by alexiglesias31** [comment]
Yes @message-dimke, merging after solve the conflicts.

**Pull request merged**
